const express = require('express');
const fs = require('fs');
const path = require('path');
const app = express();
const PORT = 3000;

// Path to the shared data generated by Python
const DATA_PATH = path.join(__dirname, '../dat/json/dashboard_stats.json');

// Serve static files from 'public' directory
app.use(express.static('public'));

// API Endpoint to get stats
app.get('/api/stats', (req, res) => {
    fs.readFile(DATA_PATH, 'utf8', (err, data) => {
        if (err) {
            console.error("Error reading stats file:", err);
            // Return default data if file is missing/corrupt
            return res.json({
                current_datetime: "System Offline",
                weather: { 
                    location: "Unknown", 
                    temperature_c: 0, 
                    condition: "N/A",
                    humidity_percent: 0
                },
                frequent_analytics: {}
            });
        }
        try {
            const jsonData = JSON.parse(data);
            res.json(jsonData);
        } catch (parseErr) {
            console.error("Error parsing JSON:", parseErr);
            res.status(500).json({ error: "Invalid JSON data" });
        }
    });
});

app.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}/dashboard.html`);
});
